config/routes.rb
Rails.application.routes.draw do
    get 'sessions/new'

    root 'static_pages#home'

    get 'home' => 'static_pages#home'
    get 'about' => 'static_pages#about'
    get 'contact' => 'static_pages#contact'

    get 'new' =>  'books#new'
    get 'loan' =>  'books#loan'
    get 'return' =>  'books#return'
    get 'loan_to' =>  'books#loan_to'

    get 'signup' => 'users#new'
    get 'extension' =>  'users#extension'
    get 'show_user_test' =>  'users#show'

    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    resources :users do
        member do
            put 'toggle'
            put 'promote'
        end
    end
    resources :books do
        member do
            put 'toggle'
        end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    validates :last_name, presence: true, length: { maximum: 50 }
    validates :phone_nb, presence: true, length: { maximum: 10 }
    validates :addr1, presence: true, length: { maximum: 200 }
    validates :addr2, length: { maximum: 200 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    has_many :book

    def self.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def self.search(search, _id)
        if search
            where('name LIKE ? OR last_name LIKE ?',
                  "%#{search}%", "%#{search}%")
        else
            all
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update]
    before_action :correct_user_or_admin, only: [:edit, :update]
    before_action :admin_user, only: [:destroy, :toggle]
    before_action :unlogged_or_admin, only: [:new, :create]

    def show
        @user = User.find(params[:id])
        redirect_to '/home' if @user.admin? && !current_user.admin?
    end

    def index
        @user = User.search(params[:search], params[:id]).paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id unless logged_in?
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:success] = 'Profile updated'
            redirect_to @user
        else
            render 'edit'
        end
      end

    def destroy
        User.find(params[:id]).destroy
        flash[:success] = 'User deleted'
        redirect_to users_url
    end

    def toggle
        @user = User.find(params[:id])
        @user.toggle!(:is_active)
        redirect_to :back
    end

    def promote
        @user = User.find(params[:id])
        @user.toggle!(:admin)
        redirect_to :back
    end

    def extension
        @book = Book.find(params[:id])

        if 30.days.from_now <= @book.max_due_date
            @book.due_date = 30.days.from_now
            redirect_to current_user if @book.save
        else
            flash[:danger] = 'You cannot ask for another extension'
            redirect_to :back
        end
    end

    private

    def unlogged_or_admin
        redirect_to(root_url) unless !logged_in? || current_user.admin?
    end

    def user_params
        params.require(:user).permit(:name, :last_name, :email, :addr1, :addr2, :phone_nb, :password, :password_confirmation)
    end

    def logged_in_user
        unless logged_in?
            flash[:danger] = 'Please log in.'
            redirect_to login_url
        end
      end

    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

    def correct_user_or_admin
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: 'gravatar')
    end

    def is_active?(user)
        user.is_active?
    end

    def is_admin? user
        user.is_admin?
    end
end

app/views/users/_admin.html.erb
<div class="row">
    <%= link_to "Add a Book", '/new', class:"btn btn-primary" %>
    <%= link_to "Add a User", '/signup', class:"btn btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<%= f.label :name, "First Name*" %>
<%= f.text_field :name , class: 'form-control'%>

<%= f.label :last_name, "Last Name*" %>
<%= f.text_field :last_name, class: 'form-control' %>

<%= f.label :email, "Email address*" %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :addr1, "Address 1*" %>
<%= f.text_field :addr1, class: 'form-control' %>

<%= f.label :addr2, "Address 2" %>
<%= f.text_field :addr2, class: 'form-control' %>

<%= f.label :phone_nb, "Phone number*" %>
<%= f.text_field :phone_nb, class: 'form-control' %>

<%= f.label :password, "Password*" %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Password confirmation*" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>


<p>*mandatory fields</p>
<%= f.submit "Save", class: "btn btn-primary" %>

<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  <% if user.is_active == true %>
  | <%= link_to "Disable", toggle_user_path(user), method: :put %>
  <% else  %>
  | <%= link_to "Enable", toggle_user_path(user), method: :put %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update
    <%= @user.name %>
    's profile</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
        <br>
        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank" class="btn btn-primary">change</a>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<% if current_user && current_user.admin? %>

<h1>All users</h1>

<div class="input-group row">
	<%= form_tag users_path, :method => 'get', :class => 'navbar-form' do %>
	<span class="input-group-btn">
		<%= text_field_tag :search, params[:search], placeholder: "Search a user", :class => 'form-control' %>
		<%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
	</span>
	<% end %>
</div>

<div id=".pagination" class="container">
	<div class="row" align=center>
		<%= will_paginate @user, inner_window: 1, outer_window: 2 %>
	</div>

	<ul class="list-group col-md-8 col-md-offset-2" style="{float: left;}">
		<% @user.each do |user| %>
		<li class="list-group-item">
			<div class="row">
				<div class="col-md-4">
					<%= gravatar_for user %>
				</div>
				<div class="col-md-2">
					<%= link_to user.name, user %>
				</div>

				<% if current_user.admin? && !current_user?(user) %>
				<div class="col-md-2">
					<%= link_to "Edit", edit_user_path(user), class: 'btn btn-primary' %>
				</div>
					<% if user.admin? == true %>
				<div class="col-md-2" >
					<%= link_to "Demote", promote_user_path(user), method: :put, class: 'btn btn-danger' %>
				</div>
					<% else  %>
				<div class="col-md-2" >
					  <%= link_to "Promote", promote_user_path(user), method: :put, class: 'btn btn-success' %>
				</div>
				<% end %>
				
				<% if user.is_active == true %>
				<div class="col-md-2" align=right>
					<%= link_to "Disable", toggle_user_path(user), method: :put, class: 'btn btn-danger' %>
				</div>
			<% else  %>
				<div class="col-md-2" align=right>
					<%= link_to "Enable", toggle_user_path(user), method: :put, class: 'btn btn-success' %>
				</div>
				<% end %>
				
				<% end %>
			</div>

		</li>
		<% end %>
	</ul>

	<div class="row" align=center>
		<%= will_paginate @user, inner_window: 1, outer_window: 2 %>
	</div>
</div>
<div class="row" align=right>
	<%= link_to "Add a User", '/signup', class:"btn btn-lg btn-primary" %>
</div>

<%end%>

app/views/users/new.html.erb
<% provide(:title, 'Sign-Up') %>
<h1>Sign Up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">

        <%= render 'form' %>

    </div>
</div>

app/views/users/show.html.erb
<%= provide :title, @user.name %>
<div class="container">
    <div class="row">
        <h1>
            <%= gravatar_for @user %>
            <%= @user.name %>
            <%= @user.last_name %>
        </h1>
    </div>
    <div class="row">
        <p>
            Email:
            <%= @user.email %>
        </p>
    </div>
    <div class="row">
        <p>
            Address:
            <%= @user.addr1 %>
        </p>

    </div>
    <% if !@user.addr2.empty? %>
    <div class="row">
        <p>
            Address2:
            <%= @user.addr2 %>
        </p>
    </div>
    <% end %>
    <div class="row">
        <p>
            Phone Number:
            <%= @user.phone_nb %>
        </p>
    </div>
    <% if current_user.admin? || current_user.id == @user.id %>
    <div class="row">
        <p>
            Is Active:
            <%= @user.is_active %>
        </p>
    </div>

    <br/>
    <% if @user.book %>
    <div class="row">
        <p>Your books:<p/>
            <%= render 'shared/error_messages' %>

            <div class="container table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Author</th>
                            <th>ISBN</th>
                            <th>Status</th>
                            <th>Due date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @user.book.each do |b| %>
                        <tr>
                            <td><%= b.title %></td>
                            <td><%= b.author %></td>
                            <td><%= b.isbn_num %></td>
                            <td><%= b.status %></td>
                            <td><%= b.due_date %></td>
                            <td><%= link_to 'Show', b %></td>
                            <td><%= link_to 'Ask for a 30 days extension',
                        extension_path(id: b) %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
        <% end %>
        <% end %>

        <div class="row" align=right>
            <span>
                <%= link_to "View our books", books_path, class: " btn btn-primary" %>
                <% if logged_in? && current_user == @user%>
                <%= link_to 'Edit my profile', edit_user_path(@user), class: "btn btn-primary"%>
                <% elsif logged_in? && current_user.admin? %>
                <%= link_to 'Edit this profile', edit_user_path(@user), class: "btn btn-primary"%>
                <% end%>
            </span>
        </div>
        <br/>
        <% if current_user.admin? && @user.admin %>
        <div class="row" align=right>
            <span>
                <%= link_to "Add a Book", '/new', class:"btn btn-primary" %>
                <%= link_to "Add a User", '/signup', class:"btn btn-primary" %>
            </span>
        </div>
        <% end %>
    </div>