config/routes.rb
Rails.application.routes.draw do
    get 'sessions/new'

    root 'static_pages#home'

    get 'home' => 'static_pages#home'
    get 'about' => 'static_pages#about'
    get 'contact' => 'static_pages#contact'

    get 'new' =>  'books#new'
    get 'loan' =>  'books#loan'
    get 'return' =>  'books#return'
    get 'loan_to' =>  'books#loan_to'

    get 'signup' => 'users#new'
    get 'extension' =>  'users#extension'
    get 'show_user_test' =>  'users#show'

    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    resources :users do
        member do
            put 'toggle'
            put 'promote'
        end
    end
    resources :books do
        member do
            put 'toggle'
        end
    end

end

app/models/book.rb
class Book < ActiveRecord::Base
    enum status: [:Available, :OnLoan, :Unavailable]

    validates :title, presence: true, length: { maximum: 50 }
    validates :author, presence: true, length: { maximum: 50 }
    validates :isbn_num, presence: true, length: { maximum: 50 }
    validates :description, length: { maximum: 300 }

    @status ||= :Available

    has_attached_file :picture, styles: { small: '150x150>' },
                                url: '/assets/products/:id/:style/:basename.:extension',
                                path: ':rails_root/public/assets/products/:id/:style/:basename.:extension'

    # validates_attachment_presence :picture
    validates_attachment_size :picture, less_than: 5.megabytes
    validates_attachment_content_type :picture, content_type: ['image/jpeg', 'image/png']

    def self.search(search, _id)
        if search
            where('title LIKE ? OR author LIKE ? OR isbn_num LIKE ?',
                  "%#{search}%", "%#{search}%", "%#{search}%")
        else
            all
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :logged_in_user, only: [:index, :show]
    before_action :admin_user, only: [:edit, :toggle, :new, :create, :update, :loan]

    def new
        @book = Book.new
    end

    def create
        @book = Book.create(book_params)

        if @book.save
            redirect_to books_path
        else
            render 'new'
        end
    end

    def update
        @book = Book.find(params[:id])

        if @book.update(book_params)
            redirect_to action: 'show'
        else
            render 'edit'
        end
    end

    def toggle
        @book = Book.find(params[:id])

        if @book.status == 'Unavailable'
            @book.status = :Available
        elsif @book.status == 'Available'
            @book.status = :Unavailable
        end

        redirect_to books_path if @book.save
    end

    def loan
        @book = Book.find(params[:id])

        if @book.status != 'Available'
            flash[:danger] = 'This book connot be loaned out'
            redirect_to books_path
        else
            @users = User.search(params[:search], params[:id]).paginate(page: params[:page], per_page: 5)
        end
    end

    def return
        @book = Book.find(params[:id])

        @book.due_date = ''
        @book.max_due_date = ''
        @book.user_id = ''
        @book.status = :Available

        redirect_to :back if @book.save
    end

    def loan_to
        @book = Book.find(params[:book_id])
        @user = User.find(params[:user_id])

        @book.due_date = 30.days.from_now
        @book.max_due_date = 90.days.from_now
        @book.status = :OnLoan
        @book.user_id = @user.id

        @user = @book

        redirect_to books_path if @book.save
    end

    def edit
        @book = Book.find(params[:id])
    end

    def index
        @books = Book.search(params[:search], params[:id]).paginate(page: params[:page], per_page: 10)
    end

    def show
        @book = Book.find(params[:id])
    end

    private

    def book_params
        params.require(:book).permit(:title, :author, :isbn_num, :description, :picture, :status)
    end

    def logged_in_user
        unless logged_in?
            flash[:danger] = 'Please log in.'
            redirect_to login_url
        end
    end

    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :multipart => true } do |f| %>

<%= render 'shared/error_messages' %>

<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>

<%= f.label :author %>
<%= f.text_field :author, class: 'form-control'%>

<%= f.label :isbn_num, "ISBN" %>
<%= f.text_field :isbn_num, class: 'form-control'%>

<%= f.label :description %>
<%= f.text_field :description, class: 'form-control'%>

<%= f.label :picture %>
<%= f.file_field :picture %>

<%= f.label :status %>
<%= f.select(:status, options_for_select(Book.statuses.keys.to_a, f.object.status), {}, {class: 'form-control'}) %>

<br/>

<div class="row">
    <div class="col-md-6">
        <%= link_to "Cancel", books_path, class: "btn btn-lg btn-block btn-danger" %>
    </div>
    <div class="col-md-6">
        <%= f.submit "Save", class: "btn btn-lg btn-primary btn-block " %>
    </div>
</div>
<% end %>

app/views/books/edit.html.erb
<%= provide(:title, 'Edit a book') %>

<% if current_user && current_user.admin? %>
<h1>Edit book</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>
<% end %>

app/views/books/index.html.erb
<% provide(:title, 'List books') %>
<h1>List of books</h1>

<% if current_user %>
<div class="input-group" align=right>
    <%= form_tag books_path, :method => 'get', :class => 'navbar-form' do %>
    <span class="input-group-btn">
        <%= text_field_tag :search, params[:search], placeholder: "Search a book", :class => 'form-control' %>
        <%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
    </span>
</div>
<% end %>
<div class="container table-responsive">

    <%= will_paginate @books %>
    <table class="table table-hover">
        <thead>
            <tr>
              <% if current_user.admin? %>
                <th>ID</th>
              <% end %>
                <th>Title</th>
                <th>Author</th>
                <th>ISBN</th>
                <th>Status</th>
                <th>Due date</th>
            </tr>
        </thead>
        <tbody>
            <% @books.each do |b| %>
            <% if current_user.admin? || b.status != 'Unavailable' %>

            <% if b.status == 'Available' %>
            <tr>
                <% elsif b.status == 'OnLoan' %>
                <tr class="info">
                <% else %>
                    <tr class="danger">
                        <% end %>
                        <% if current_user.admin? %>
                          <td><%= b.id %></td>
                        <% end %>
                        <td><%= b.title %></td>
                        <td><%= b.author %></td>
                        <td><%= b.isbn_num %></td>
                        <td><%= b.status %></td>
                        <td><%= b.due_date %></td>
                        <td><%= link_to 'Show', b %></td>
                        <% if current_user.admin? %>
                        <% if b.status == 'Available' %>
                        <td><%= link_to "Loan this book", loan_path(id: b) %></td>
                        <% elsif b.status == 'OnLoan' %>
                        <td><%= link_to "Mark this book as returned", return_path(id: b) %></td>
                    <% else %>
                        <td/>
                        <% end %>
                        <td><%= link_to 'Edit', edit_book_path(b) %></td>
                        <% if b.status != 'OnLoan' %>
                        <td><%= link_to "Change active state", toggle_book_path(b), method: :put %></td>
                    <% else %>
                        <td/>
                        <% end %>
                        <% end %>
                    </tr>
                    <% end %>
                    <% end %>
                </tbody>
            </table>
            <%= will_paginate @books %>

        </div>

    <% else %>
        <p>Please, log in to see our list of books</p>
        <%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-primary" %>
        <tr/>
        <%= link_to "Log in", 'login', class: "btn btn-lg btn-primary" %>
        <%- end -%>

        <% if current_user && current_user.admin? %>
        <br/>
        <div class="row" align=right>
            <%= link_to "Add a new book", 'new', class: "btn btn-lg btn-primary" %>
        </div>
        <%- end -%>

app/views/books/loan.html.erb
<%= provide(:title, 'Loan a book') %>

<% if current_user && current_user.admin? %>
<h1>Loan a book</h1>

<div class="container">
    <div class="input-group row">
        <%= form_tag loan_path, :method => 'get', :class => 'navbar-form' do %>
        <span class="input-group-btn">
            <%= text_field_tag :search, params[:search], placeholder: "Search a user", :class => 'form-control' %>
            <%= hidden_field_tag :id , @book.id %>
            <%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
        </span>
        <% end %>
    </div>

    <div class="row" align=center>
        <%= will_paginate @users, inner_window: 1, outer_window: 2 %>
    </div>

    <ul class="list-group col-md-6 col-md-offset-3">
        <% @users.each do |user| %>
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-4">
                    <%= gravatar_for user %>
                </div>
                <div class="col-md-2">
                    <%= link_to user.name, user %>
                </div>

                <div class="col-md-4" align=right>
                    <%= link_to "Loan to this user",
                      loan_to_path(book_id: @book, user_id: user), class: 'btn btn-primary' %>
                </div>
            </div>

        </li>
        <% end %>
    </ul>

    <div class="row" align=center>
        <%= will_paginate @users, inner_window: 1, outer_window: 2 %>
    </div>
</div>

<% end %>

app/views/books/new.html.erb
<%= provide(:title, 'Add a book') %>

<% if current_user && current_user.admin? %>
<h1>Add book</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>
<% end %>

app/views/books/show.html.erb
<%= provide(:title, @book.title) %>

<% if current_user %>

<h1>View a book</h1>
<div class="row">

    <%= image_tag @book.picture.url(:small) %>
    <br/><br/>

    <% if current_user.admin? %>
    <p>
        <strong>ID:</strong>
        <%= @book.id %>
    </p>
    <% end %>

    <p>
        <strong>Title:</strong>
        <%= @book.title %>
    </p>

    <p>
        <strong>Author:</strong>
        <%= @book.author %>
    </p>

    <p>
        <strong>ISBN:</strong>
        <%= @book.isbn_num %>
    </p>

    <p>
        <strong>Description:</strong>
        <%= @book.description %>
    </p>

    <p>
        <strong>Status:</strong>
        <%= @book.status %>
    </p>
</div>

<%= link_to "Back to the list", books_path, class: "btn btn-lg btn-primary" %>

<% if current_user.admin? %>
<%= link_to 'Edit', edit_book_path(@book), class: "btn btn-lg btn-primary" %>
<% end %>
<% end %>