config/routes.rb
Rails.application.routes.draw do
    get 'sessions/new'

    root 'static_pages#home'

    get 'home' => 'static_pages#home'
    get 'about' => 'static_pages#about'
    get 'contact' => 'static_pages#contact'

    get 'new' =>  'books#new'
    get 'loan' =>  'books#loan'
    get 'return' =>  'books#return'
    get 'loan_to' =>  'books#loan_to'

    get 'signup' => 'users#new'
    get 'extension' =>  'users#extension'
    get 'show_user_test' =>  'users#show'

    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'

    resources :users do
        member do
            put 'toggle'
            put 'promote'
        end
    end
    resources :books do
        member do
            put 'toggle'
        end
    end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
            </ul>
        </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Library", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <% if logged_in? %>
                <% if current_user.admin? %>
                <li><%= link_to "User List", users_path %></li>
                <li><%= link_to "Book List", books_path %></li>
                <% end %>
                <li><%= link_to current_user.name, current_user %></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
        </li>
    <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
    </ul>
</nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]> <script scr="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script> <![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
        </div>

        <%= render 'layouts/footer' %>

    </body>
</html>